export default {
    path: '/iocn',
    name: 'iocn',
    component: () => import('/@/layout/routerView/parent.vue'),
    redirect: '/iocn/iocnfont',
    meta: {
        title: 'message.router.iocnfont',
        isLink: '',
        isHide: false,
        isKeepAlive: true,
        isAffix: false,
        isIframe: false,
        roles: ['admin', 'common'],
        icon: 'ele-Grape',
    },
    children: [
        {
            path: '/iocn/iocnfont',
            name: 'iocnIocnfont',
            component: () => import('/@/views/iocn/iocnfont/index.vue'),
            meta: {
                title: 'message.router.iocnIocnfont',
                isLink: '',
                isHide: false,
                isKeepAlive: true,
                isAffix: false,
                isIframe: false,
                roles: ['admin', 'common'],
                icon: 'ele-Present',
            },
        },
        {
            path: '/iocn/element',
            name: 'iocnElement',
            component: () => import('/@/views/iocn/element/index.vue'),
            meta: {
                title: 'message.router.iocnElement',
                isLink: '',
                isHide: false,
                isKeepAlive: true,
                isAffix: false,
                isIframe: false,
                roles: ['admin', 'common'],
                icon: 'ele-ElementPlus',
            },
        },
        {
            path: '/iocn/awesome',
            name: 'iocnAwesome',
            component: () => import('/@/views/iocn/awesome/index.vue'),
            meta: {
                title: 'message.router.iocnAwesome',
                isLink: '',
                isHide: false,
                isKeepAlive: true,
                isAffix: false,
                isIframe: false,
                roles: ['admin', 'common'],
                icon: 'ele-SetUp',
            },
        },
    ],
}