export default {
    path: '/pages',
    name: 'pagesIndex',
    component: () => import('/@/layout/routerView/parent.vue'),
    redirect: '/pages/filtering',
    meta: {
        title: 'message.router.pagesIndex',
        isLink: '',
        isHide: false,
        isKeepAlive: true,
        isAffix: false,
        isIframe: false,
        roles: ['admin', 'common'],
        icon: 'iconfont icon-fuzhiyemian',
    },
    children: [
        {
            path: '/pages/filtering',
            name: 'pagesFiltering',
            component: () => import('/@/views/pages/filtering/index.vue'),
            meta: {
                title: 'message.router.pagesFiltering',
                isLink: '',
                isHide: false,
                isKeepAlive: true,
                isAffix: false,
                isIframe: false,
                roles: ['admin', 'common'],
                icon: 'ele-Sell',
            },
            /**
             * 注意此处详情写法：
             * 1、嵌套进父级里时，面包屑显示为：首页/页面/过滤筛选组件/过滤筛选组件详情
             * 2、不嵌套进父级时，面包屑显示为：首页/页面/过滤筛选组件/过滤筛选组件详情
             * 3、想要父级不高亮，面包屑显示为：首页/页面/过滤筛选组件详情，设置路径为：/pages/filteringDetails
             */
            children: [
                {
                    path: '/pages/filtering/details',
                    name: 'pagesFilteringDetails',
                    component: () => import('/@/views/pages/filtering/details.vue'),
                    meta: {
                        title: 'message.router.pagesFilteringDetails',
                        isLink: '',
                        isHide: true,
                        isKeepAlive: false,
                        isAffix: false,
                        isIframe: false,
                        roles: ['admin', 'common'],
                        icon: 'ele-Sunny',
                    },
                },
            ],
        },
        {
            path: '/pages/filtering/details1',
            name: 'pagesFilteringDetails1',
            component: () => import('/@/views/pages/filtering/details1.vue'),
            meta: {
                title: 'message.router.pagesFilteringDetails1',
                isLink: '',
                isHide: true,
                isKeepAlive: false,
                isAffix: false,
                isIframe: false,
                roles: ['admin', 'common'],
                icon: 'ele-Sunny',
            },
        }, {
            path: '/pages/fadeUp',
            name: 'fadeUp',
            component: () => import('/@/views/pages/fadeUp/index.vue'),
            meta: {
                title: 'message.router.pagesFadeUp',
                isLink: '',
                isHide: false,
                isKeepAlive: true,
                isAffix: false,
                isIframe: false,
                roles: ['admin', 'common'],
                icon: 'iconfont icon-jinridaiban',
            },
        }, {
            path: '/pages/tableRules',
            name: 'pagesTableRules',
            component: () => import('/@/views/pages/tableRules/index.vue'),
            meta: {
                title: 'message.router.pagesTableRules',
                isLink: '',
                isHide: false,
                isKeepAlive: true,
                isAffix: false,
                isIframe: false,
                roles: ['admin', 'common'],
                icon: 'iconfont icon-jiliandongxuanzeqi',
            },
        },
        {
            path: '/pages/formRules',
            name: 'pagesFormRules',
            component: () => import('/@/views/pages/formRules/index.vue'),
            meta: {
                title: 'message.router.pagesFormRules',
                isLink: '',
                isHide: false,
                isKeepAlive: true,
                isAffix: false,
                isIframe: false,
                roles: ['admin', 'common'],
                icon: 'iconfont icon-shuxing',
            },
        },
        {
            path: '/pages/waterfall',
            name: 'pagesWaterfall',
            component: () => import('/@/views/pages/waterfall/index.vue'),
            meta: {
                title: 'message.router.pagesWaterfall',
                isLink: '',
                isHide: false,
                isKeepAlive: true,
                isAffix: false,
                isIframe: false,
                roles: ['admin', 'common'],
                icon: 'iconfont icon-zidingyibuju',
            },
        },
        {
            path: '/pages/tree',
            name: 'pagesTree',
            component: () => import('/@/views/pages/tree/index.vue'),
            meta: {
                title: 'message.router.pagesTree',
                isLink: '',
                isHide: false,
                isKeepAlive: true,
                isAffix: false,
                isIframe: false,
                roles: ['admin', 'common'],
                icon: 'iconfont icon-shuxingtu',
            },
        },
        {
            path: '/pages/lazyImg',
            name: 'pagesLazyImg',
            component: () => import('/@/views/pages/lazyImg/index.vue'),
            meta: {
                title: 'message.router.pagesLazyImg',
                isLink: '',
                isHide: false,
                isKeepAlive: true,
                isAffix: false,
                isIframe: false,
                roles: ['admin'],
                icon: 'ele-PictureFilled',
            },
        },
        {
            path: '/pages/dynamicForm',
            name: 'pagesDynamicForm',
            component: () => import('/@/views/pages/dynamicForm/index.vue'),
            meta: {
                title: 'message.router.pagesDynamicForm',
                isLink: '',
                isHide: false,
                isKeepAlive: true,
                isAffix: false,
                isIframe: false,
                roles: ['admin'],
                icon: 'iconfont icon-wenducanshu-05',
            },
        },
        {
            path: '/pages/workflow',
            name: 'pagesWorkflow',
            component: () => import('/@/views/pages/workflow/index.vue'),
            meta: {
                title: 'message.router.pagesWorkflow',
                isLink: '',
                isHide: false,
                isKeepAlive: true,
                isAffix: false,
                isIframe: false,
                roles: ['admin'],
                icon: 'ele-Connection',
            },
        },
    ],
}