export default {
	path: '/basic',
	name: 'basic',
	redirect: '/basic/basicConfig',
	meta: {
		icon: 'Menu',
		order: 3,
		requiresAuth: true,
		title: '系统维护',
		isLink: '',
		isHide: false,
		isFull: false,
		isAffix: false,
		isKeepAlive: true,
	},
	children: [
		{
			path: '/basic/basicConfig',
			name: 'basicConfig',
			meta: {
				icon: 'Menu',
				requiresAuth: true,
				title: '基础参数配置',
				isLink: '',
				isHide: false,
				isFull: false,
				isAffix: false,
				isKeepAlive: true,
			},
			component: () => import('@/views/basic/basicConfig/index.vue'),
		},
		{
			path: '/basic/monitor',
			name: 'monitor',
			redirect: '/basic/monitor/job',
			meta: {
				icon: 'Menu',
				requiresAuth: true,
				title: '任务调度',
				isLink: '',
				isHide: false,
				isFull: false,
				isAffix: false,
				isKeepAlive: true,
			},
			children: [
				{
					path: '/basic/monitor/job',
					name: 'job',
					component: () => import('@/views/basic/monitor/job/index.vue'),
					meta: {
						icon: 'Menu',
						requiresAuth: true,
						title: '任务作业调度',
						activeMenu: '/basic/monitor',
						isLink: '',
						isHide: true,
						isFull: false,
						isAffix: false,
						isKeepAlive: true,
					},
					children: [
						{
							path: '/basic/monitor/job/detail/:id',
							name: 'jobDetail',
							component: () => import('@/views/basic/monitor/job/detail/index.vue'),
							meta: {
								icon: 'Menu',
								requiresAuth: true,
								title: '调度日志',
								activeMenu: '/basic/monitor/job',
								isLink: '',
								isHide: true,
								isFull: false,
								isAffix: false,
								isKeepAlive: true,
							},
						},
					],
				},
			],
		},
	],
};
