export default {
	path: '/inspection',
	name: 'inspection',
	redirect: '/inspection/inspectionStandard',
	meta: {
		icon: 'Menu',
		order: 6,
		requiresAuth: true,
		title: '点检标准',
		isLink: '',
		isHide: false,
		isFull: false,
		isAffix: false,
		isKeepAlive: true,
	},
	children: [
		{
			path: '/inspection/inspectionStandard',
			name: 'inspectionStandard',
			meta: {
				icon: 'Menu',
				requiresAuth: true,
				title: '点检项目列表',
				isLink: '',
				isHide: false,
				isFull: false,
				isAffix: false,
				isKeepAlive: true,
			},
			component: () => import('@/views/inspection/inspectionStandard/index.vue'),
		},
		{
			path: '/inspection/inspectionMonthReport/:reportId',
			name: 'report',
			meta: {
				icon: 'Menu',
				// activeMenu: '/inspection/inspectionMonthReport',
				requiresAuth: true,
				title: '点检结果月度报表',
				isLink: '',
				isHide: true,
				isFull: false,
				isAffix: false,
				isKeepAlive: true,
			},
			component: () => import('@/views/inspection/inspectionMonthReport/report/index.vue'),
		},
	],
};
