export default {
	path: '/system',
	name: 'System',
	redirect: '/system/user',
	meta: {
		icon: 'Menu',
		order: 2,
		requiresAuth: true,
		title: '系统管理',
		isLink: '',
		isHide: false,
		isFull: false,
		isAffix: false,
		isKeepAlive: true,
	},
	children: [
		{
			path: '/system/user',
			name: 'user',
			meta: {
				icon: 'User',
				requiresAuth: true,
				title: '用户管理',
				isLink: '',
				isHide: false,
				isFull: false,
				isAffix: false,
				isKeepAlive: true,
			},
			component: () => import('@/views/system/user/index.vue'),
		},
		{
			path: '/system/menu',
			name: 'menu',
			meta: {
				icon: 'Menu',
				requiresAuth: true,
				title: '菜单管理',
				isLink: '',
				isHide: false,
				isFull: false,
				isAffix: false,
				isKeepAlive: true,
			},
			component: () => import('@/views/system/menu/index.vue'),
		},
		{
			path: '/system/dept',
			name: 'dept',
			meta: {
				icon: 'Cherry',
				requiresAuth: true,
				title: '部门管理',
				isLink: '',
				isHide: false,
				isFull: false,
				isAffix: false,
				isKeepAlive: true,
			},
			component: () => import('@/views/system/dept/index.vue'),
		},
		{
			path: '/system/role',
			name: 'role',
			meta: {
				icon: 'UserFilled',
				requiresAuth: true,
				title: '角色管理',
				isLink: '',
				isHide: false,
				isFull: false,
				isAffix: false,
				isKeepAlive: true,
			},
			component: () => import('@/views/system/role/index.vue'),
		},
		{
			path: '/system/post',
			name: 'post',
			meta: {
				icon: 'UserFilled',
				requiresAuth: true,
				title: '岗位管理',
				isLink: '',
				isHide: false,
				isFull: false,
				isAffix: false,
				isKeepAlive: true,
			},
			component: () => import('@/views/system/post/index.vue'),
		},
		{
			path: '/system/log',
			name: 'log',
			meta: {
				icon: 'UserFilled',
				requiresAuth: true,
				title: '日志管理',
				isLink: '',
				isHide: false,
				isFull: false,
				isAffix: false,
				isKeepAlive: true,
			},
			children: [
				{
					path: '/system/log/operlog',
					name: 'operlog',
					meta: {
						icon: 'User',
						requiresAuth: true,
						title: '操作日志',
						isLink: '',
						isHide: false,
						isFull: false,
						isAffix: false,
						isKeepAlive: true,
					},
					component: () => import('@/views/system/log/operlog/index.vue'),
				},
				{
					path: '/system/log/logininfor',
					name: 'logininfor',
					meta: {
						icon: 'User',
						requiresAuth: true,
						title: '登录日志',
						isLink: '',
						isHide: false,
						isFull: false,
						isAffix: false,
						isKeepAlive: true,
					},
					component: () => import('@/views/system/log/logininfor/index.vue'),
				},
			],
		},
		{
			path: '/system/dict',
			name: 'dict',
			component: () => import('@/views/system/dict/index.vue'),
			meta: {
				icon: 'Menu',
				requiresAuth: true,
				title: '数据字典',
				isLink: '',
				isHide: false,
				isFull: false,
				isAffix: false,
				isKeepAlive: true,
			},
			children: [
				{
					path: '/system/dict/detail/:id',
					name: 'dictDetail',
					component: () => import('@/views/system/dict/detail/index.vue'),
					meta: {
						icon: 'Menu',
						requiresAuth: true,
						title: '数据字典详情',
						activeMenu: '/system/dict',
						isLink: '',
						isHide: true,
						isFull: false,
						isAffix: false,
						isKeepAlive: true,
					},
				},
			],
		},
	],
};
