export default {
	path: '/fun',
	name: 'funIndex',
	component: () => import('/@/layout/routerView/parent.vue'),
	redirect: '/fun/tagsView',
	meta: {
		title: 'message.router.funIndex',
		isLink: '',
		isHide: false,
		isKeepAlive: true,
		isAffix: false,
		isIframe: false,
		roles: ['admin', 'common'],
		icon: 'iconfont icon-caidan',
	},
	children: [
		{
			path: '/fun/tagsView',
			name: 'funTagsView',
			component: () => import('/@/views/fun/tagsView/index.vue'),
			meta: {
				title: 'message.router.funTagsView',
				isLink: '',
				isHide: false,
				isKeepAlive: true,
				isAffix: false,
				isIframe: false,
				roles: ['admin', 'common'],
				icon: 'ele-Pointer',
			},
		},
		{
			path: '/fun/countUp',
			name: 'funCountUp',
			component: () => import('/@/views/fun/countUp/index.vue'),
			meta: {
				title: 'message.router.funCountUp',
				isLink: '',
				isHide: false,
				isKeepAlive: true,
				isAffix: false,
				isIframe: false,
				roles: ['admin', 'common'],
				icon: 'ele-Odometer',
			},
		},
		{
			path: '/fun/wangEditor',
			name: 'funWangEditor',
			component: () => import('/@/views/fun/wangEditor/index.vue'),
			meta: {
				title: 'message.router.funWangEditor',
				isLink: '',
				isHide: false,
				isKeepAlive: true,
				isAffix: false,
				isIframe: false,
				roles: ['admin', 'common'],
				icon: 'iconfont icon-fuwenbenkuang',
			},
		},
		{
			path: '/fun/cropper',
			name: 'funCropper',
			component: () => import('/@/views/fun/cropper/index.vue'),
			meta: {
				title: 'message.router.funCropper',
				isLink: '',
				isHide: false,
				isKeepAlive: true,
				isAffix: false,
				isIframe: false,
				roles: ['admin', 'common'],
				icon: 'iconfont icon-iconfont_jiandao',
			},
		},
		{
			path: '/fun/draggable',
			name: 'funDraggable',
			component: () => import('/@/views/fun/draggable/index.vue'),
			meta: {
				title: 'message.router.funDraggable',
				isLink: '',
				isHide: false,
				isKeepAlive: true,
				isAffix: false,
				isIframe: false,
				roles: ['admin', 'common'],
				icon: 'iconfont icon-tuodong',
			},
		},
		{
			path: '/fun/qrcode',
			name: 'funQrcode',
			component: () => import('/@/views/fun/qrcode/index.vue'),
			meta: {
				title: 'message.router.funQrcode',
				isLink: '',
				isHide: false,
				isKeepAlive: true,
				isAffix: false,
				isIframe: false,
				roles: ['admin', 'common'],
				icon: 'iconfont icon-ico',
			},
		},
		/**
		 * 打开内置全屏
		 *  全局浏览
		 * component 都为 `() => import('/@/layout/routerView/link.vue')`
		 * isLink 链接为内置的路由地址，地址为 staticRoutes 中定义
		 */
		{
			path: '/fun/printJs',
			name: 'funPrintJs',
			component: () => import('/@/views/fun/printJs/index.vue'),
			meta: {
				title: 'message.router.funPrintJs',
				isLink: '',
				isHide: false,
				isKeepAlive: true,
				isAffix: false,
				isIframe: false,
				roles: ['admin', 'common'],
				icon: 'ele-Printer',
			},
		},
		{
			path: '/fun/clipboard',
			name: 'funClipboard',
			component: () => import('/@/views/fun/clipboard/index.vue'),
			meta: {
				title: 'message.router.funClipboard',
				isLink: '',
				isHide: false,
				isKeepAlive: true,
				isAffix: false,
				isIframe: false,
				roles: ['admin', 'common'],
				icon: 'ele-DocumentCopy',
			},
		},
		{
			path: '/fun/gridLayout',
			name: 'funGridLayout',
			component: () => import('/@/views/fun/gridLayout/index.vue'),
			meta: {
				title: 'message.router.funGridLayout',
				isLink: '',
				isHide: false,
				isKeepAlive: true,
				isAffix: false,
				isIframe: false,
				roles: ['admin', 'common'],
				icon: 'iconfont icon-iconfonticon51',
			},
		},
		{
			path: '/fun/splitpanes',
			name: 'funSplitpanes',
			component: () => import('/@/views/fun/splitpanes/index.vue'),
			meta: {
				title: 'message.router.funSplitpanes',
				isLink: '',
				isHide: false,
				isKeepAlive: true,
				isAffix: false,
				isIframe: false,
				roles: ['admin', 'common'],
				icon: 'iconfont icon--chaifenlie',
			},
		},
		{
			path: '/fun/drag',
			name: 'funDrag',
			component: () => import('/@/views/fun/drag/index.vue'),
			meta: {
				title: 'message.router.funDrag',
				isLink: '',
				isHide: false,
				isKeepAlive: true,
				isAffix: false,
				isIframe: false,
				roles: ['admin', 'common'],
				icon: 'ele-Pointer',
			},
		},
		{
			path: '/fun/waves',
			name: 'funWaves',
			component: () => import('/@/views/fun/waves/index.vue'),
			meta: {
				title: 'message.router.funWaves',
				isLink: '',
				isHide: false,
				isKeepAlive: true,
				isAffix: false,
				isIframe: false,
				roles: ['admin', 'common'],
				icon: 'iconfont icon-bolangneng',
			},
		},
		{
			path: '/fun/colorExtractor',
			name: 'funColorExtractor',
			component: () => import('/@/views/fun/colorExtractor/index.vue'),
			meta: {
				title: 'message.router.funColorExtractor',
				isLink: '',
				isHide: false,
				isKeepAlive: true,
				isAffix: false,
				isIframe: false,
				roles: ['admin', 'common'],
				icon: 'iconfont icon-iconfont_bi',
			},
		},
		{
			path: '/fun/typed',
			name: 'funTyped',
			component: () => import('/@/views/fun/typed/index.vue'),
			meta: {
				title: 'message.router.funTyped',
				isLink: '',
				isHide: false,
				isKeepAlive: true,
				isAffix: false,
				isIframe: false,
				roles: ['admin'],
				icon: 'ele-EditPen',
			},
		},
		{
			path: '/fun/screenshot',
			name: 'funScreenshot',
			component: () => import('/@/views/fun/screenshot/index.vue'),
			meta: {
				title: 'message.router.funScreenshot',
				isLink: '',
				isHide: false,
				isKeepAlive: true,
				isAffix: false,
				isIframe: false,
				roles: ['admin'],
				icon: 'ele-Crop',
			},
		},
	],
};
