export default {
    path: '/limits',
    name: 'limits',
    component: () => import('/@/layout/routerView/parent.vue'),
    redirect: '/limits/frontEnd',
    meta: {
        title: 'message.router.limits',
        isLink: '',
        isHide: false,
        isKeepAlive: true,
        isAffix: false,
        isIframe: false,
        roles: ['admin', 'common'],
        icon: 'iconfont icon-shuxingtu',
    },
    children: [
        {
            path: '/limits/frontEndPage',
            name: 'limitsFrontEndPage',
            component: () => import('/@/views/limits/frontEndPage/index.vue'),
            meta: {
                title: 'message.router.limitsFrontEndPage',
                isLink: '',
                isHide: false,
                isKeepAlive: true,
                isAffix: false,
                isIframe: false,
                roles: ['admin', 'common'],
                icon: 'iconfont icon-zhongduancanshuchaxun',
            },
        },
        {
            path: '/limits/frontEndBbtn',
            name: 'limitsFrontEndBtn',
            component: () => import('/@/views/limits/frontEndBtn/index.vue'),
            meta: {
                title: 'message.router.limitsFrontEndBtn',
                isLink: '',
                isHide: false,
                isKeepAlive: true,
                isAffix: false,
                isIframe: false,
                roles: ['admin', 'common'],
                icon: 'iconfont icon-shuxing',
            },
        },
    ],
}