export default {
	path: '/make',
	name: 'makeIndex',
	component: () => import('/@/layout/routerView/parent.vue'),
	redirect: '/make/selector',
	meta: {
		title: 'message.router.makeIndex',
		isLink: '',
		isHide: false,
		isKeepAlive: true,
		isAffix: false,
		isIframe: false,
		roles: ['admin'],
		icon: 'iconfont icon-zujian',
	},
	children: [
		{
			path: '/make/selector',
			name: 'makeSelector',
			component: () => import('/@/views/make/selector/index.vue'),
			meta: {
				title: 'message.router.makeSelector',
				isLink: '',
				isHide: false,
				isKeepAlive: true,
				isAffix: false,
				isIframe: false,
				roles: ['admin', 'common'],
				icon: 'ele-InfoFilled',
			},
		},
		{
			path: '/make/noticeBar',
			name: 'makeNoticeBar',
			component: () => import('/@/views/make/noticeBar/index.vue'),
			meta: {
				title: 'message.router.makeNoticeBar',
				isLink: '',
				isHide: false,
				isKeepAlive: true,
				isAffix: false,
				isIframe: false,
				roles: ['admin', 'common'],
				icon: 'ele-Bell',
			},
		},
		{
			path: '/make/svgDemo',
			name: 'makeSvgDemo',
			component: () => import('/@/views/make/svgDemo/index.vue'),
			meta: {
				title: 'message.router.makeSvgDemo',
				isLink: '',
				isHide: false,
				isKeepAlive: true,
				isAffix: false,
				isIframe: false,
				roles: ['admin', 'common'],
				icon: 'fa fa-thumbs-o-up',
			},
		},
		{
			path: '/make/formDrawer',
			name: 'makeFormDrawer',
			component: () => import('/@/views/make/formDrawer/index.vue'),
			meta: {
				title: 'message.router.makeFormDrawer',
				isLink: '',
				isHide: false,
				isKeepAlive: true,
				isAffix: false,
				isIframe: false,
				roles: ['admin', 'common'],
				icon: 'ele-MessageBox',
			},
		},
		{
			path: '/make/selectFilter',
			name: 'makeSelectFilter',
			component: () => import('/@/views/make/selectFilter/index.vue'),
			meta: {
				title: 'message.router.makeSelectFilter',
				isLink: '',
				isHide: false,
				isKeepAlive: true,
				isAffix: false,
				isIframe: false,
				roles: ['admin', 'common'],
				icon: 'ele-Postcard',
			},
		},
	],
};
