export default {
	path: '/map',
	name: 'map',
	component: () => import('/@/layout/routerView/parent.vue'),
	redirect: '/map/baidu',
	meta: {
		title: 'message.router.map',
		isLink: '',
		isHide: false,
		isKeepAlive: true,
		isAffix: false,
		isIframe: false,
		roles: ['admin'],
		icon: 'iconfont icon-ditu',
	},
	children: [
		{
			path: '/map/baidu',
			name: 'mapBaidu',
			component: () => import('/@/views/map/baidu/index.vue'),
			meta: {
				title: 'message.router.mapBaidu',
				isLink: '',
				isHide: false,
				isKeepAlive: true,
				isAffix: false,
				isIframe: false,
				roles: ['admin', 'common'],
				icon: 'iconfont icon-diqiu1',
			},
		},
		{
			path: '/map/gaode',
			name: 'mapGaode',
			component: () => import('/@/views/map/gaode/index.vue'),
			meta: {
				title: 'message.router.mapGaode',
				isLink: '',
				isHide: false,
				isKeepAlive: true,
				isAffix: false,
				isIframe: false,
				roles: ['admin', 'common'],
				icon: 'iconfont icon-diqiu',
			},
		},
		{
			path: '/map/echartsMap',
			name: 'mapEcharts',
			component: () => import('/@/views/map/mapEcharts/index.vue'),
			meta: {
				title: 'message.router.mapEcharts',
				isLink: '',
				isHide: false,
				isKeepAlive: true,
				isAffix: false,
				isIframe: false,
				roles: ['admin', 'common'],
				icon: 'iconfont icon-xingqiu',
			},
		},
		{
			path: '/map/chartEcharts',
			name: 'chartEcharts',
			component: () => import('/@/views/map/chartEcharts/index.vue'),
			meta: {
				title: 'message.router.chartEcharts',
				isLink: '',
				isHide: false,
				isKeepAlive: true,
				isAffix: false,
				isIframe: false,
				roles: ['admin', 'common'],
				icon: 'iconfont icon-xingqiu',
			},
		},
	],
};
