export default {
	path: '/pages',
	name: 'pagesIndex',
	component: () => import('/@/layout/routerView/parent.vue'),
	redirect: '/pages/filtering',
	meta: {
		title: 'message.router.pagesIndex',
		isLink: '',
		isHide: false,
		isKeepAlive: true,
		isAffix: false,
		isIframe: false,
		roles: ['admin', 'common'],
		icon: 'ele-DocumentCopy',
	},
	children: [
		{
			path: '/pages/fadeUp',
			name: 'fadeUp',
			component: () => import('/@/views/pages/fadeUp/index.vue'),
			meta: {
				title: 'message.router.pagesFadeUp',
				isLink: '',
				isHide: false,
				isKeepAlive: true,
				isAffix: false,
				isIframe: false,
				roles: ['admin', 'common'],
				icon: 'iconfont icon-jinridaiban',
			},
		},
		{
			path: '/pages/tableRules',
			name: 'pagesTableRules',
			component: () => import('/@/views/pages/tableRules/index.vue'),
			meta: {
				title: 'message.router.pagesTableRules',
				isLink: '',
				isHide: false,
				isKeepAlive: true,
				isAffix: false,
				isIframe: false,
				roles: ['admin', 'common'],
				icon: 'iconfont icon-jiliandongxuanzeqi',
			},
		},
		{
			path: '/pages/formRules',
			name: 'pagesFormRules',
			component: () => import('/@/views/pages/formRules/index.vue'),
			meta: {
				title: 'message.router.pagesFormRules',
				isLink: '',
				isHide: false,
				isKeepAlive: true,
				isAffix: false,
				isIframe: false,
				roles: ['admin', 'common'],
				icon: 'iconfont icon-shuxing',
			},
		},
		{
			path: '/pages/waterfall',
			name: 'pagesWaterfall',
			component: () => import('/@/views/pages/waterfall/index.vue'),
			meta: {
				title: 'message.router.pagesWaterfall',
				isLink: '',
				isHide: false,
				isKeepAlive: true,
				isAffix: false,
				isIframe: false,
				roles: ['admin', 'common'],
				icon: 'iconfont icon-zidingyibuju',
			},
		},
		{
			path: '/pages/treeTable',
			name: 'pagesTreeTable',
			component: () => import('/@/views/pages/treeTable/index.vue'),
			meta: {
				title: 'message.router.pagesTreeTable',
				isLink: '',
				isHide: false,
				isKeepAlive: true,
				isAffix: false,
				isIframe: false,
				roles: ['admin', 'common'],
				icon: 'iconfont icon-shuxingtu',
			},
		},
		{
			path: '/pages/lazyImg',
			name: 'pagesLazyImg',
			component: () => import('/@/views/pages/lazyImg/index.vue'),
			meta: {
				title: 'message.router.pagesLazyImg',
				isLink: '',
				isHide: false,
				isKeepAlive: true,
				isAffix: false,
				isIframe: false,
				roles: ['admin'],
				icon: 'ele-PictureFilled',
			},
		},
		{
			path: '/pages/dynamicForm',
			name: 'pagesDynamicForm',
			component: () => import('/@/views/pages/dynamicForm/index.vue'),
			meta: {
				title: 'message.router.pagesDynamicForm',
				isLink: '',
				isHide: false,
				isKeepAlive: true,
				isAffix: false,
				isIframe: false,
				roles: ['admin'],
				icon: 'iconfont icon-wenducanshu-05',
			},
		},
		{
			path: '/pages/workflow',
			name: 'pagesWorkflow',
			component: () => import('/@/views/pages/workflow/index.vue'),
			meta: {
				title: 'message.router.pagesWorkflow',
				isLink: '',
				isHide: false,
				isKeepAlive: true,
				isAffix: false,
				isIframe: false,
				roles: ['admin'],
				icon: 'ele-Connection',
			},
		},
		{
			path: '/pages/tableDemo',
			name: 'pagesTableDemo',
			component: () => import('/@/views/pages/tableDemo/index.vue'),
			meta: {
				title: 'message.router.pagesTableDemo',
				isLink: '',
				isHide: false,
				isKeepAlive: true,
				isAffix: false,
				isIframe: false,
				roles: ['admin', 'common'],
				icon: 'iconfont icon-huoyuedu-',
			},
		},
		{
			path: '/pages/tableDemo2',
			name: 'pagesTableDemo2',
			component: () => import('/@/views/pages/tableDemo2/index.vue'),
			meta: {
				title: 'message.router.pagesTableDemo2',
				isLink: '',
				isHide: false,
				isKeepAlive: true,
				isAffix: false,
				isIframe: false,
				roles: ['admin', 'common'],
				icon: 'iconfont icon-huoyuedu-',
			},
		},
		{
			path: '/pages/tableDemo2/operate',
			name: 'pagesTableDemo2Operate',
			component: () => import('/@/views/pages/tableDemo2/operate/index.vue'),
			meta: {
				title: 'message.router.pagesTableDemo2Operate',
				superiorName: 'pagesTableDemo2',
				isLink: '',
				isHide: true,
				isKeepAlive: true,
				isAffix: false,
				isIframe: false,
				roles: ['admin', 'common'],
				icon: 'iconfont icon-huoyuedu-',
			},
		},
		{
			path: '/pages/treeSelector',
			name: 'pagesTreeSelector',
			component: () => import('/@/views/pages/treeSelector/index.vue'),
			meta: {
				title: 'message.router.pagesTreeSelector',
				isLink: '',
				isHide: false,
				isKeepAlive: true,
				isAffix: false,
				isIframe: false,
				roles: ['admin', 'common'],
				icon: 'ele-Cherry',
			},
		},
		{
			path: '/pages/dargBoard',
			name: 'pagesDargBoard',
			component: () => import('/@/views/pages/dargBoard/index.vue'),
			meta: {
				title: 'message.router.pagesDargBoard',
				isLink: '',
				isHide: false,
				isKeepAlive: true,
				isAffix: false,
				isIframe: false,
				roles: ['admin', 'common'],
				icon: 'ele-DataBoard',
			},
		},
	],
};
