export default {
	path: '/assembly',
	name: 'assembly',
	redirect: '/assembly/guide',
	meta: {
		icon: 'Briefcase',
		order: 5,
		requiresAuth: true,
		title: '常用组件',
		isLink: '',
		isHide: false,
		isFull: false,
		isAffix: false,
		isKeepAlive: true,
	},
	children: [
		{
			path: '/assembly/guide',
			name: 'guide',
			meta: {
				icon: 'Menu',
				requiresAuth: true,
				title: '引导页',
				isLink: '',
				isHide: false,
				isFull: false,
				isAffix: false,
				isKeepAlive: true,
			},
			component: () => import('@/views/assembly/guide/index.vue'),
		},
		{
			path: '/assembly/tabs',
			name: 'tabs',
			meta: {
				icon: 'Menu',
				requiresAuth: true,
				title: '标签页操作',
				isLink: '',
				isHide: false,
				isFull: false,
				isAffix: false,
				isKeepAlive: true,
			},
			children: [
				{
					path: '/assembly/tabs/detail/:id',
					name: 'tabsDetail',
					meta: {
						icon: 'Menu',
						requiresAuth: true,
						title: 'Tab 详情',
						activeMenu: '/assembly/tabs',
						isLink: '',
						isHide: true,
						isFull: false,
						isAffix: false,
						isKeepAlive: true,
					},
					component: () => import('@/views/assembly/tabs/detail.vue'),
				},
			],
			component: () => import('@/views/assembly/tabs/index.vue'),
		},
		{
			path: '/assembly/selectIcon',
			name: 'selectIcon',
			meta: {
				icon: 'Menu',
				requiresAuth: true,
				title: '图标选择器',
				isLink: '',
				isHide: false,
				isFull: false,
				isAffix: false,
				isKeepAlive: true,
			},
			component: () => import('@/views/assembly/selectIcon/index.vue'),
		},
		{
			path: '/assembly/selectFilter',
			name: 'selectFilter',
			meta: {
				icon: 'Menu',
				requiresAuth: true,
				title: '分类筛选器',
				isLink: '',
				isHide: false,
				isFull: false,
				isAffix: false,
				isKeepAlive: true,
			},
			component: () => import('@/views/assembly/selectFilter/index.vue'),
		},
		{
			path: '/assembly/treeSelector',
			name: 'treeSelector',
			meta: {
				icon: 'Menu',
				requiresAuth: true,
				title: '树形筛选器',
				isLink: '',
				isHide: false,
				isFull: false,
				isAffix: false,
				isKeepAlive: true,
			},
			component: () => import('@/views/assembly/treeSelector/index.vue'),
		},
		{
			path: '/assembly/svgIcon',
			name: 'svgIcon',
			meta: {
				icon: 'Menu',
				requiresAuth: true,
				title: 'SVG 图标',
				isLink: '',
				isHide: false,
				isFull: false,
				isAffix: false,
				isKeepAlive: true,
			},
			component: () => import('@/views/assembly/svgIcon/index.vue'),
		},
		{
			path: '/assembly/wangEditor',
			name: 'wangEditor',
			meta: {
				icon: 'Menu',
				requiresAuth: true,
				title: '富文本编辑器',
				isLink: '',
				isHide: false,
				isFull: false,
				isAffix: false,
				isKeepAlive: true,
			},
			component: () => import('@/views/assembly/wangEditor/index.vue'),
		},
		{
			path: '/assembly/draggable',
			name: 'draggable',
			meta: {
				icon: 'Menu',
				requiresAuth: true,
				title: '拖拽组件',
				isLink: '',
				isHide: false,
				isFull: false,
				isAffix: false,
				isKeepAlive: true,
			},
			component: () => import('@/views/assembly/draggable/index.vue'),
		},
	],
};
