/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Auth: typeof import('./components/auth/auth.vue')['default']
    AuthAll: typeof import('./components/auth/authAll.vue')['default']
    Auths: typeof import('./components/auth/auths.vue')['default']
    Chart: typeof import('./components/chart/index.vue')['default']
    ColorExtractor: typeof import('./components/colorExtractor/index.vue')['default']
    Content: typeof import('./components/content/index.vue')['default']
    copy: typeof import('./components/selectFilter copy/index.vue')['default']
    CountUp: typeof import('./components/countUp/index.vue')['default']
    CropperJs: typeof import('./components/cropperJs/index.vue')['default']
    CustomTable: typeof import('./components/customTable/index.vue')['default']
    CustomTableMould: typeof import('./components/customTableMould/index.vue')['default']
    FlopTime: typeof import('./components/flopTime/index.vue')['default']
    FormDrawer: typeof import('./components/formDrawer/index.vue')['default']
    IconSelector: typeof import('./components/iconSelector/index.vue')['default']
    List: typeof import('./components/iconSelector/list.vue')['default']
    NoticeBar: typeof import('./components/noticeBar/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchItem: typeof import('./components/searchItem/index.vue')['default']
    SelectFilter: typeof import('./components/selectFilter/index.vue')['default']
    SvgIcon: typeof import('./components/svgIcon/index.vue')['default']
    TablePlus: typeof import('./components/tablePlus/index.vue')['default']
    TestCom: typeof import('./components/testCom/index.vue')['default']
    TreeFilter: typeof import('./components/treeFilter/index.vue')['default']
    VueCropper: typeof import('./components/vueCropper/index.vue')['default']
    WangEditor: typeof import('./components/wangEditor/index.vue')['default']
  }
}
