/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    403: typeof import('./components/ErrorMessage/403.vue')['default']
    404: typeof import('./components/ErrorMessage/404.vue')['default']
    500: typeof import('./components/ErrorMessage/500.vue')['default']
    Container: typeof import('./components/Container/index.vue')['default']
    CustomTableMould: typeof import('./components/CustomTableMould/index.vue')['default']
    Dot: typeof import('./components/Dot/index.vue')['default']
    ECharts: typeof import('./components/ECharts/index.vue')['default']
    FlopTime: typeof import('./components/FlopTime/index.vue')['default']
    Loading: typeof import('./components/Loading/index.vue')['default']
    MultiIcon: typeof import('./components/MultiIcon/index.vue')['default']
    NoticeBar: typeof import('./components/NoticeBar/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchItem: typeof import('./components/SearchItem/index.vue')['default']
    SelectFilter: typeof import('./components/SelectFilter/index.vue')['default']
    SelectIcon: typeof import('./components/SelectIcon/index.vue')['default']
    SvgIcon: typeof import('./components/SvgIcon/index.vue')['default']
    SwitchDark: typeof import('./components/SwitchDark/index.vue')['default']
    TablePlus: typeof import('./components/TablePlus/index.vue')['default']
    TagInput: typeof import('./components/TagInput/index.vue')['default']
    TreeSelector: typeof import('./components/TreeSelector/index.vue')['default']
    VueCropper: typeof import('./components/VueCropper/index.vue')['default']
    WangEditor: typeof import('./components/WangEditor/index.vue')['default']
  }
}
