/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    403: typeof import('./components/ErrorMessage/403.vue')['default']
    404: typeof import('./components/ErrorMessage/404.vue')['default']
    500: typeof import('./components/ErrorMessage/500.vue')['default']
    Container: typeof import('./components/Container/index.vue')['default']
    Crontab: typeof import('./components/Crontab/index.vue')['default']
    CustomTableMould: typeof import('./components/CustomTableMould/index.vue')['default']
    Day: typeof import('./components/Crontab/day.vue')['default']
    ECharts: typeof import('./components/ECharts/index.vue')['default']
    Hour: typeof import('./components/Crontab/hour.vue')['default']
    Loading: typeof import('./components/Loading/index.vue')['default']
    Min: typeof import('./components/Crontab/min.vue')['default']
    Month: typeof import('./components/Crontab/month.vue')['default']
    Result: typeof import('./components/Crontab/result.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchItem: typeof import('./components/SearchItem/index.vue')['default']
    Second: typeof import('./components/Crontab/second.vue')['default']
    SelectFilter: typeof import('./components/SelectFilter/index.vue')['default']
    SelectIcon: typeof import('./components/SelectIcon/index.vue')['default']
    Statistic: typeof import('./components/Statistic/index.vue')['default']
    SwitchDark: typeof import('./components/SwitchDark/index.vue')['default']
    TablePlus: typeof import('./components/TablePlus/index.vue')['default']
    TreeSelector: typeof import('./components/TreeSelector/index.vue')['default']
    WangEditor: typeof import('./components/WangEditor/index.vue')['default']
    Week: typeof import('./components/Crontab/week.vue')['default']
    Year: typeof import('./components/Crontab/year.vue')['default']
  }
}
