export default {
	path: '/assembly',
	name: 'assembly',
	redirect: '/assembly/selectIcon',
	meta: {
		icon: 'Briefcase',
		order: 5,
		requiresAuth: true,
		title: '常用组件',
		isLink: '',
		isHide: false,
		isFull: false,
		isAffix: false,
		isKeepAlive: true,
	},
	children: [
		{
			path: '/assembly/selectIcon',
			name: 'selectIcon',
			meta: {
				icon: 'Menu',
				requiresAuth: true,
				title: '图标选择器',
				isLink: '',
				isHide: false,
				isFull: false,
				isAffix: false,
				isKeepAlive: true,
			},
			component: () => import('@/views/assembly/selectIcon/index.vue'),
		},
		{
			path: '/assembly/selectFilter',
			name: 'selectFilter',
			meta: {
				icon: 'Menu',
				requiresAuth: true,
				title: '分类筛选器',
				isLink: '',
				isHide: false,
				isFull: false,
				isAffix: false,
				isKeepAlive: true,
			},
			component: () => import('@/views/assembly/selectFilter/index.vue'),
		},
		{
			path: '/assembly/treeSelector',
			name: 'treeSelector',
			meta: {
				icon: 'Menu',
				requiresAuth: true,
				title: '树形筛选器',
				isLink: '',
				isHide: false,
				isFull: false,
				isAffix: false,
				isKeepAlive: true,
			},
			component: () => import('@/views/assembly/treeSelector/index.vue'),
		},
		{
			path: '/assembly/svgIcon',
			name: 'svgIcon',
			meta: {
				icon: 'Menu',
				requiresAuth: true,
				title: 'SVG 图标',
				isLink: '',
				isHide: false,
				isFull: false,
				isAffix: false,
				isKeepAlive: true,
			},
			component: () => import('@/views/assembly/svgIcon/index.vue'),
		},
		{
			path: '/assembly/wangEditor',
			name: 'wangEditor',
			meta: {
				icon: 'Menu',
				requiresAuth: true,
				title: '富文本编辑器',
				isLink: '',
				isHide: false,
				isFull: false,
				isAffix: false,
				isKeepAlive: true,
			},
			component: () => import('@/views/assembly/wangEditor/index.vue'),
		},
	],
};
