export default {
	path: '/assembly',
	name: 'assembly',
	redirect: '/assembly/selectIcon',
	meta: {
		icon: 'Briefcase',
		order: 5,
		title: '常用组件',
		isLink: '',
		isHide: false,
		isFull: false,
		isAffix: false,
		isKeepAlive: true,
	},
	children: [
		{
			path: '/assembly/selectIcon',
			name: 'selectIcon',
			component: '/assembly/selectIcon/index',
			meta: {
				icon: 'Menu',
				title: '图标选择器',
				isLink: '',
				isHide: false,
				isFull: false,
				isAffix: false,
				isKeepAlive: true,
			},
		},
		{
			path: '/assembly/selectFilter',
			name: 'selectFilter',
			component: '/assembly/selectFilter/index',
			meta: {
				icon: 'Menu',
				title: '分类筛选器',
				isLink: '',
				isHide: false,
				isFull: false,
				isAffix: false,
				isKeepAlive: true,
			},
		},
		{
			path: '/assembly/treeSelector',
			name: 'treeSelector',
			component: '/assembly/treeSelector/index',
			meta: {
				icon: 'Menu',
				title: '树形筛选器',
				isLink: '',
				isHide: false,
				isFull: false,
				isAffix: false,
				isKeepAlive: true,
			},
		},
		{
			path: '/assembly/svgIcon',
			name: 'svgIcon',
			component: '/assembly/svgIcon/index',
			meta: {
				icon: 'Menu',
				title: 'SVG 图标',
				isLink: '',
				isHide: false,
				isFull: false,
				isAffix: false,
				isKeepAlive: true,
			},
		},
		{
			path: '/assembly/wangEditor',
			name: 'wangEditor',
			component: '/assembly/wangEditor/index',
			meta: {
				icon: 'Menu',
				title: '富文本编辑器',
				isLink: '',
				isHide: false,
				isFull: false,
				isAffix: false,
				isKeepAlive: true,
			},
		},
		{
			path: '/assembly/draggable',
			name: 'draggable',
			component: '/assembly/draggable/index',
			meta: {
				icon: 'Menu',
				title: '拖拽组件',
				isLink: '',
				isHide: false,
				isFull: false,
				isAffix: false,
				isKeepAlive: true,
			},
		},
	],
};
