export default {
	path: '/echarts',
	name: 'echarts',
	redirect: '/echarts/waterChart',
	meta: {
		icon: 'TrendCharts',
		order: 11,
		requiresAuth: true,
		title: 'ECharts',
		isLink: '',
		isHide: false,
		isFull: false,
		isAffix: false,
		isKeepAlive: true,
	},
	children: [
		{
			path: '/echarts/waterChart',
			name: 'waterChart',
			meta: {
				icon: 'Menu',
				requiresAuth: true,
				title: '水型图',
				isLink: '',
				isHide: false,
				isFull: false,
				isAffix: false,
				isKeepAlive: true,
			},
			component: () => import('@/views/echarts/waterChart/index.vue'),
		},
		{
			path: '/echarts/columnChart',
			name: 'columnChart',
			meta: {
				icon: 'Menu',
				requiresAuth: true,
				title: '柱状图',
				isLink: '',
				isHide: false,
				isFull: false,
				isAffix: false,
				isKeepAlive: true,
			},
			component: () => import('@/views/echarts/columnChart/index.vue'),
		},
		{
			path: '/echarts/lineChart',
			name: 'lineChart',
			meta: {
				icon: 'Menu',
				requiresAuth: true,
				title: '折线图',
				isLink: '',
				isHide: false,
				isFull: false,
				isAffix: false,
				isKeepAlive: true,
			},
			component: () => import('@/views/echarts/lineChart/index.vue'),
		},
		{
			path: '/echarts/pieChart',
			name: 'pieChart',
			meta: {
				icon: 'Menu',
				requiresAuth: true,
				title: '饼图',
				isLink: '',
				isHide: false,
				isFull: false,
				isAffix: false,
				isKeepAlive: true,
			},
			component: () => import('@/views/echarts/pieChart/index.vue'),
		},
		{
			path: '/echarts/radarChart',
			name: 'radarChart',
			meta: {
				icon: 'Menu',
				requiresAuth: true,
				title: '雷达图',
				isLink: '',
				isHide: false,
				isFull: false,
				isAffix: false,
				isKeepAlive: true,
			},
			component: () => import('@/views/echarts/radarChart/index.vue'),
		},
		{
			path: '/echarts/nestedChart',
			name: 'nestedChart',
			meta: {
				icon: 'Menu',
				requiresAuth: true,
				title: '嵌套环形图',
				isLink: '',
				isHide: false,
				isFull: false,
				isAffix: false,
				isKeepAlive: true,
			},
			component: () => import('@/views/echarts/nestedChart/index.vue'),
		},
	],
};
