export default {
	path: '/function',
	name: 'function',
	redirect: '/function/tabs',
	meta: {
		icon: 'Coin',
		order: 6,
		requiresAuth: true,
		title: '功能插件',
		isLink: '',
		isHide: false,
		isFull: false,
		isAffix: false,
		isKeepAlive: true,
	},
	children: [
		{
			path: '/function/tabs',
			name: 'tabs',
			meta: {
				icon: 'Menu',
				requiresAuth: true,
				title: '标签页操作',
				isLink: '',
				isHide: false,
				isFull: false,
				isAffix: false,
				isKeepAlive: true,
			},
			children: [
				{
					path: '/function/tabs/detail/:id',
					name: 'tabsDetail',
					meta: {
						icon: 'Menu',
						requiresAuth: true,
						title: 'Tab 详情',
						activeMenu: '/function/tabs',
						isLink: '',
						isHide: true,
						isFull: false,
						isAffix: false,
						isKeepAlive: true,
					},
					component: () => import('@/views/function/tabs/detail.vue'),
				},
			],
			component: () => import('@/views/function/tabs/index.vue'),
		},
		{
			path: '/function/draggable',
			name: 'draggable',
			meta: {
				icon: 'Menu',
				requiresAuth: true,
				title: '拖拽组件',
				isLink: '',
				isHide: false,
				isFull: false,
				isAffix: false,
				isKeepAlive: true,
			},
			component: () => import('@/views/function/draggable/index.vue'),
		},
		{
			path: '/function/formRules',
			name: 'formRules',
			meta: {
				icon: 'Menu',
				requiresAuth: true,
				title: '多表单验证',
				isLink: '',
				isHide: false,
				isFull: false,
				isAffix: false,
				isKeepAlive: true,
			},
			component: () => import('@/views/function/formRules/index.vue'),
		},
		{
			path: '/function/tableRules',
			name: 'tableRules',
			meta: {
				icon: 'Menu',
				requiresAuth: true,
				title: '表格验证',
				isLink: '',
				isHide: false,
				isFull: false,
				isAffix: false,
				isKeepAlive: true,
			},
			component: () => import('@/views/function/tableRules/index.vue'),
		},
		{
			path: '/function/anchorPoint',
			name: 'anchorPoint',
			meta: {
				icon: 'Menu',
				requiresAuth: true,
				title: '锚点滚动',
				isLink: '',
				isHide: false,
				isFull: false,
				isAffix: false,
				isKeepAlive: true,
			},
			component: () => import('@/views/function/anchorPoint/index.vue'),
		},
		{
			path: '/function/qrCode',
			name: 'qrCode',
			meta: {
				icon: 'Menu',
				requiresAuth: true,
				title: '二维码',
				isLink: '',
				isHide: false,
				isFull: false,
				isAffix: false,
				isKeepAlive: true,
			},
			component: () => import('@/views/function/qrCode/index.vue'),
		},
		{
			path: '/function/splitpanes',
			name: 'splitpanes',
			meta: {
				icon: 'Menu',
				requiresAuth: true,
				title: '窗格拆分器',
				isLink: '',
				isHide: false,
				isFull: false,
				isAffix: false,
				isKeepAlive: true,
			},
			component: () => import('@/views/function/splitpanes/index.vue'),
		},
		{
			path: '/function/gridLayout',
			name: 'gridLayout',
			meta: {
				icon: 'Menu',
				requiresAuth: true,
				title: '栅格拖拽布局',
				isLink: '',
				isHide: false,
				isFull: false,
				isAffix: false,
				isKeepAlive: true,
			},
			component: () => import('@/views/function/gridLayout/index.vue'),
		},
		{
			path: '/function/miniPlugin',
			name: 'miniPlugin',
			meta: {
				icon: 'Menu',
				requiresAuth: true,
				title: '小插件',
				isLink: '',
				isHide: false,
				isFull: false,
				isAffix: false,
				isKeepAlive: true,
			},
			component: () => import('@/views/function/miniPlugin/index.vue'),
		},
	],
};
