export default {
	path: '/icon',
	name: 'icon',
	redirect: '/icon/awesome',
	meta: {
		icon: 'Grape',
		title: '图标管理',
		order: 8,
		isLink: '',
		isHide: false,
		isFull: false,
		isAffix: false,
		requiresAuth: true,
		isKeepAlive: true,
	},
	children: [
		{
			path: '/icon/awesome',
			name: 'awesome',
			meta: {
				icon: 'Menu',
				title: 'awe字体图标',
				isLink: '',
				isHide: false,
				isFull: false,
				isAffix: false,
				requiresAuth: true,
				isKeepAlive: true,
			},
			component: () => import('@/views/icon/awesome/index.vue'),
		},
		{
			path: '/icon/element',
			name: 'element',
			meta: {
				icon: 'Menu',
				title: 'ele字体图标',
				isLink: '',
				isHide: false,
				isFull: false,
				isAffix: false,
				requiresAuth: true,
				isKeepAlive: true,
			},
			component: () => import('@/views/icon/element/index.vue'),
		},
		{
			path: '/icon/iocnfont',
			name: 'iocnfont',
			meta: {
				icon: 'Menu',
				title: 'ali字体图标',
				isLink: '',
				isHide: false,
				isFull: false,
				isAffix: false,
				requiresAuth: true,
				isKeepAlive: true,
			},
			component: () => import('@/views/icon/iocnfont/index.vue'),
		},
	],
};
