export default {
	path: '/menu',
	name: 'menu',
	redirect: '/menu/menu1',
	meta: {
		icon: 'List',
		order: 8,
		requiresAuth: true,
		title: '菜单嵌套',
		isLink: '',
		isHide: false,
		isFull: false,
		isAffix: false,
		isKeepAlive: true,
	},
	children: [
		{
			path: '/menu/menu1',
			name: 'menu1',
			meta: {
				icon: 'Menu',
				requiresAuth: true,
				title: '菜单1',
				isLink: '',
				isHide: false,
				isFull: false,
				isAffix: false,
				isKeepAlive: true,
			},
			component: () => import('@/views/menu/menu1/index.vue'),
		},
		{
			path: '/menu/menu2',
			name: 'menu2',
			redirect: '/menu/menu2/menu21',
			meta: {
				icon: 'Menu',
				requiresAuth: true,
				title: '菜单2',
				isLink: '',
				isHide: false,
				isFull: false,
				isAffix: false,
				isKeepAlive: true,
			},
			children: [
				{
					path: '/menu/menu2/menu21',
					name: 'menu21',
					meta: {
						icon: 'Menu',
						requiresAuth: true,
						title: '菜单2-1',
						isLink: '',
						isHide: false,
						isFull: false,
						isAffix: false,
						isKeepAlive: true,
					},
					component: () => import('@/views/menu/menu2/menu21/index.vue'),
				},
				{
					path: '/menu/menu2/menu22',
					name: 'menu22',
					redirect: '/menu/menu2/menu22/menu221',
					meta: {
						icon: 'Menu',
						requiresAuth: true,
						title: '菜单2-2',
						isLink: '',
						isHide: false,
						isFull: false,
						isAffix: false,
						isKeepAlive: true,
					},
					children: [
						{
							path: '/menu/menu2/menu22/menu221',
							name: 'menu221',
							meta: {
								icon: 'Menu',
								requiresAuth: true,
								title: '菜单2-2-1',
								isLink: '',
								isHide: false,
								isFull: false,
								isAffix: false,
								isKeepAlive: true,
							},
							component: () => import('@/views/menu/menu2/menu22/menu221/index.vue'),
						},
						{
							path: '/menu/menu2/menu22/menu222',
							name: 'menu222',
							meta: {
								icon: 'Menu',
								requiresAuth: true,
								title: '菜单2-2-2',
								isLink: '',
								isHide: false,
								isFull: false,
								isAffix: false,
								isKeepAlive: true,
							},
							component: () => import('@/views/menu/menu2/menu22/menu222/index.vue'),
						},
					],
				},
			],
		},
	],
};
