export default {
	path: '/proTable',
	name: 'proTable',
	redirect: '/proTable/useTableDemo',
	meta: {
		icon: 'MessageBox',
		order: 3,
		requiresAuth: true,
		title: '表格菜单',
		isLink: '',
		isHide: false,
		isFull: false,
		isAffix: false,
		isKeepAlive: true,
	},
	children: [
		{
			path: '/proTable/useTableDemo',
			name: 'useTableDemo',
			component: () => import('@/views/proTable/useTableDemo/index.vue'),
			meta: {
				icon: 'Menu',
				requiresAuth: true,
				title: '表格菜单Demo',
				isLink: '',
				isHide: false,
				isFull: false,
				isAffix: false,
				isKeepAlive: true,
			},
			children: [
				{
					path: '/proTable/useTableDemo/detail/:id',
					name: 'useTableDemoDetail',
					component: () => import('@/views/proTable/useTableDemo/detail/index.vue'),
					meta: {
						icon: 'Menu',
						requiresAuth: true,
						title: '表格菜单Demo详情',
						activeMenu: '/proTable/useTableDemo',
						isLink: '',
						isHide: true,
						isFull: false,
						isAffix: false,
						isKeepAlive: true,
					},
				},
			],
		},
		{
			path: '/proTable/useTableDemo2',
			name: 'useTableDemo2',
			component: () => import('@/views/proTable/useTableDemo2/index.vue'),
			meta: {
				icon: 'Menu',
				requiresAuth: true,
				title: '表格菜单Demo2',
				isLink: '',
				isHide: false,
				isFull: false,
				isAffix: false,
				isKeepAlive: true,
			},
		},
	],
};
